services:
  db:
    image: postgres:16
    
    container_name: service-bancs-yvedon
    environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: museum
    ports:
            - "5437:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./data:/data
